- hosts: db-servers
  remote_user: ubuntu
  become: true
  become_method: sudo
  vars_files:
    - vars.yaml
  vars:
    ansible_ssh_private_key_file: "{{ keys }}"
  #gather_facts: no
   
  tasks:
   - name: Update all packages
     apt: 
       update_cache: yes
       name: "*"
       state: latest
###
   - name: Set hostname
     hostname:
       name: "{{ inventory_hostname }}"
###
   - name: Install dependencies
     apt: 
      pkg:
        - ca-certificates
        - curl
        - gnupg2
        - lsb-release
        - htop
        - git-all

   - name: Install percona repo
     shell: wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb

   - name: Activate percona repo
     shell: dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb 

   - name: Set Percona dist
     shell: percona-release setup ps80

   - name: Install Percona
     apt: name=percona-server-server state=present update_cache=yes

   - name: Copy conf file
     template:
       src: templates/mysqld.cnf.j2
       dest: /etc/mysql/mysql.conf.d/mysqld.cnf
       owner: root
       group: root
       mode: 0644
    
   - name: Restart db
     systemd:
       name:  mysql
       state: restarted
